### PR TITLE
Cleaned code, removed unnecessary code, added requirement.txt

### PR DESCRIPTION
**Pull request by necromancerthedark**

### CODE REVIEW

**Review by raprocks — APPROVED** [review]

**Comment by raprocks** [comment]
Great work @necromancerthedark , thanks for the PR. I'll probably change the whole project structure in the near future, but well this is the start of it 😄 .

**Comment by raprocks** [comment]
Closed without merging hehe

**Comment by necromancerthedark** [comment]
hehe,I was going to croi ;___;
Thank you for merging :)

**Comment by raprocks** [comment]
Hehe where do i contact you apart from github comments?😂 (9nly if you wiah to be contacted that is)

**Comment by necromancerthedark** [comment]
On instagram @thatsartisting

**Pull request merged**
