### PR TITLE
Added Multi Thread support and little CLI feature

### PR DESCRIPTION
**Pull request by dwivedi-ritik**
I have added multi threading support with 5 default workers and also some command line arguments . 
I have also updated read me .
On my PC i have tested thread support , i executed [this quiz](https://www.sanfoundry.com/1000-python-questions-answers/) in 17
sec whereas normal function took 50 sec ,
Added two optional command line  `--threads` which is boolean and `--workers` takes a integer value.

### CODE REVIEW

**Comment by raprocks** [comment]
Thanks for the PR, sorry i am a little late to get around this. Ill check it and merge it ASAP. Thanks Ritik 😃 .

**Comment by dwivedi-ritik** [comment]
My Pleasure King  👑

**Comment by raprocks** [comment]
Hey @dwivedi-ritik  , can you revert back to where it was asking for the url as input? Most of the people that use the script dont know much of the CLI and find it easier that way tbh. I made the url as argument at the beginning too but well people didnt know how to use it. what do you think though? If you have a solid reason for keeping it this way then ill merge it right away! or just maybe do it so that if nothing is passed with the url flag, it asks for input. That would be something better!

**Comment by dwivedi-ritik** [comment]
Bro I have added that option .
If user doesn't passes url flag , it will  ask for user input . 
See at line 55 in main.py 

I think you added url as an input , I didn't see it as an command line arguments anywhere . This is why I added a url flag
I guess both methods will work fine , but sometimes cli can be little easier to work with . 
also user can pass url as a flag or as an input .
But I should have have added url as positional argument instead of as a flag .

**Comment by raprocks** [comment]
> Bro I have added that option .
> If user doesn't passes url flag , it will ask for user input .
> See at line 55 in main.py

damn didnt see that 😂 . merging the PR! Thanks once again for the Contribution!

**Pull request merged**
